FROM python:3.12-slim

ENV POETRY_VIRTUALENVS_IN_PROJECT=false
ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONFAULTHANDLER=1
ENV PYTHONHASHSEED=0

RUN pip install poetry 

WORKDIR /app

COPY pyproject.toml poetry.lock /app/

COPY . /app/

RUN poetry install --no-interaction

CMD ["poetry", "run","uvicorn", "src.api.run:api", "--host", "0.0.0.0", "--port", "8000"]